# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'

services:

  orderer.hf.abl.io:
    container_name: orderer.hf.abl.io
    extends:
      file: peer-base.yaml
      service: orderer-base
    environment:
      - CONFIGTX_ORDERER_KAFKA_BROKERS=[kafka.hf.abl.io:9092]
    volumes:
        - ../channel-artifacts/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
        - ../crypto-config/ordererOrganizations/hf.abl.io/orderers/orderer.hf.abl.io/msp:/var/hyperledger/orderer/msp
        - ../crypto-config/ordererOrganizations/hf.abl.io/orderers/orderer.hf.abl.io/tls/:/var/hyperledger/orderer/tls
        - orderer.hf.abl.io:/var/hyperledger/production/orderer
    ports:
      - 7050:7050

  orderer2.hf.abl.io:
    extends:
      file: peer-base.yaml
      service: orderer-base
    environment:
        - CONFIGTX_ORDERER_KAFKA_BROKERS=[kafka.hf.abl.io:9092]
    container_name: orderer2.hf.abl.io
    networks:
    - byfn
    volumes:
        - ../channel-artifacts/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
        - ../crypto-config/ordererOrganizations/hf.abl.io/orderers/orderer2.hf.abl.io/msp:/var/hyperledger/orderer/msp
        - ../crypto-config/ordererOrganizations/hf.abl.io/orderers/orderer2.hf.abl.io/tls/:/var/hyperledger/orderer/tls
        - orderer2.hf.abl.io:/var/hyperledger/production/orderer
    ports:
    - 8050:7050

  orderer3.hf.abl.io:
    extends:
      file: peer-base.yaml
      service: orderer-base
    environment:
      - CONFIGTX_ORDERER_KAFKA_BROKERS=[kafka.hf.abl.io:9092]
    container_name: orderer3.hf.abl.io
    networks:
    - byfn
    volumes:
        - ../channel-artifacts/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
        - ../crypto-config/ordererOrganizations/hf.abl.io/orderers/orderer3.hf.abl.io/msp:/var/hyperledger/orderer/msp
        - ../crypto-config/ordererOrganizations/hf.abl.io/orderers/orderer3.hf.abl.io/tls/:/var/hyperledger/orderer/tls
        - orderer3.hf.abl.io:/var/hyperledger/production/orderer
    ports:
    - 9050:7050

  peer0.org1.hf.abl.io:
    container_name: peer0.org1.hf.abl.io
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.org1.hf.abl.io
      - CORE_PEER_ADDRESS=peer0.org1.hf.abl.io:7051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:7051
      - CORE_PEER_CHAINCODEADDRESS=peer0.org1.hf.abl.io:7052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7052
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.org1.hf.abl.io:8051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.org1.hf.abl.io:7051
      - CORE_PEER_LOCALMSPID=Org1MSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/org1.hf.abl.io/peers/peer0.org1.hf.abl.io/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/org1.hf.abl.io/peers/peer0.org1.hf.abl.io/tls:/etc/hyperledger/fabric/tls
        - peer0.org1.hf.abl.io:/var/hyperledger/production
    ports:
      - 7051:7051
      - 7053:7053

  peer1.org1.hf.abl.io:
    container_name: peer1.org1.hf.abl.io
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer1.org1.hf.abl.io
      - CORE_PEER_ADDRESS=peer1.org1.hf.abl.io:8051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:8051
      - CORE_PEER_CHAINCODEADDRESS=peer1.org1.hf.abl.io:8052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:8052
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.org1.hf.abl.io:8051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.org1.hf.abl.io:7051
      - CORE_PEER_LOCALMSPID=Org1MSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/org1.hf.abl.io/peers/peer1.org1.hf.abl.io/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/org1.hf.abl.io/peers/peer1.org1.hf.abl.io/tls:/etc/hyperledger/fabric/tls
        - peer1.org1.hf.abl.io:/var/hyperledger/production
    ports:
      - 8051:8051
      - 8053:8053

  peer2.org1.hf.abl.io:
    container_name: peer2.org1.hf.abl.io
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer2.org1.hf.abl.io
      - CORE_PEER_ADDRESS=peer2.org1.hf.abl.io:9051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:9051
      - CORE_PEER_CHAINCODEADDRESS=peer2.org1.hf.abl.io:9052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:9052
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer2.org1.hf.abl.io:9051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.org1.hf.abl.io:7051
      - CORE_PEER_LOCALMSPID=Org1MSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/org1.hf.abl.io/peers/peer2.org1.hf.abl.io/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/org1.hf.abl.io/peers/peer2.org1.hf.abl.io/tls:/etc/hyperledger/fabric/tls
        - peer2.org1.hf.abl.io:/var/hyperledger/production
    ports:
      - 9051:9051
      - 9053:9053

  peer3.org1.hf.abl.io:
    container_name: peer3.org1.hf.abl.io
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer3.org1.hf.abl.io
      - CORE_PEER_ADDRESS=peer3.org1.hf.abl.io:10051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:10051
      - CORE_PEER_CHAINCODEADDRESS=peer3.org1.hf.abl.io:10052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:10052
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer3.org1.hf.abl.io:10051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.org1.hf.abl.io:7051
      - CORE_PEER_LOCALMSPID=Org1MSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/org1.hf.abl.io/peers/peer3.org1.hf.abl.io/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/org1.hf.abl.io/peers/peer3.org1.hf.abl.io/tls:/etc/hyperledger/fabric/tls
        - peer3.org1.hf.abl.io:/var/hyperledger/production
    ports:
      - 10051:10051
      - 10053:10053

  peer4.org1.hf.abl.io:
    container_name: peer4.org1.hf.abl.io
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer4.org1.hf.abl.io
      - CORE_PEER_ADDRESS=peer4.org1.hf.abl.io:11051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:11051
      - CORE_PEER_CHAINCODEADDRESS=peer4.org1.hf.abl.io:11052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:11052
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer4.org1.hf.abl.io:11051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.org1.hf.abl.io:7051
      - CORE_PEER_LOCALMSPID=Org1MSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/org1.hf.abl.io/peers/peer4.org1.hf.abl.io/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/org1.hf.abl.io/peers/peer4.org1.hf.abl.io/tls:/etc/hyperledger/fabric/tls
        - peer4.org1.hf.abl.io:/var/hyperledger/production
    ports:
      - 11051:11051
      - 11053:11053

  peer5.org1.hf.abl.io:
    container_name: peer5.org1.hf.abl.io
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer5.org1.hf.abl.io
      - CORE_PEER_ADDRESS=peer5.org1.hf.abl.io:12051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:12051
      - CORE_PEER_CHAINCODEADDRESS=peer5.org1.hf.abl.io:12052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:12052
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer5.org1.hf.abl.io:12051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.org1.hf.abl.io:7051
      - CORE_PEER_LOCALMSPID=Org1MSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/org1.hf.abl.io/peers/peer5.org1.hf.abl.io/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/org1.hf.abl.io/peers/peer5.org1.hf.abl.io/tls:/etc/hyperledger/fabric/tls
        - peer5.org1.hf.abl.io:/var/hyperledger/production
    ports:
      - 12051:12051
      - 12053:12053
