# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'

volumes:
  orderer2.hf.abl.io:
  orderer3.hf.abl.io:

networks:
  byfn:

services:

  orderer2.hf.abl.io:
    extends:
      file: base/peer-base.yaml
      service: orderer-base
    container_name: orderer2.hf.abl.io
    networks:
    - byfn
    volumes:
        - ./channel-artifacts/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
        - ./crypto-config/ordererOrganizations/hf.abl.io/orderers/orderer2.hf.abl.io/msp:/var/hyperledger/orderer/msp
        - ./crypto-config/ordererOrganizations/hf.abl.io/orderers/orderer2.hf.abl.io/tls/:/var/hyperledger/orderer/tls
        - orderer2.hf.abl.io:/var/hyperledger/production/orderer
    ports:
    - 8050:7050

  orderer3.hf.abl.io:
    extends:
      file: base/peer-base.yaml
      service: orderer-base
    container_name: orderer3.hf.abl.io
    networks:
    - byfn
    volumes:
        - ./channel-artifacts/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
        - ./crypto-config/ordererOrganizations/hf.abl.io/orderers/orderer3.hf.abl.io/msp:/var/hyperledger/orderer/msp
        - ./crypto-config/ordererOrganizations/hf.abl.io/orderers/orderer3.hf.abl.io/tls/:/var/hyperledger/orderer/tls
        - orderer3.hf.abl.io:/var/hyperledger/production/orderer
    ports:
    - 9050:7050
